/**
 * Thin wrappers around the generated React Query hooks for the pipeline-flow
 * analytics endpoints (declared in openapi.yaml, generated by Orval).
 *
 * Each endpoint returns the loose `GenericDataResponse` ({ data: <object> }),
 * so consumers read `query.data?.data` and cast to the concrete shape they
 * need (mirrors the dashboard widget pattern in use-pipeline-risk.ts).
 */
import {
  useGetFlowFunnel,
  useGetFlowConversionMatrix,
  useGetFlowSankey,
  useGetFlowRecycle,
  useGetFlowHealthScore,
  useGetFlowCoverage,
} from "@workspace/api-client-react";

export const useFlowFunnel = () => useGetFlowFunnel();

export const useFlowConversionMatrix = (windowDays?: number) =>
  useGetFlowConversionMatrix(windowDays != null ? { windowDays } : undefined);

export const useFlowSankey = (mode?: "count" | "value") =>
  useGetFlowSankey(mode != null ? { mode } : undefined);

export const useFlowRecycle = () => useGetFlowRecycle();

export const useFlowHealthScore = () => useGetFlowHealthScore();

export const useFlowCoverage = () => useGetFlowCoverage();
